Store nav items in database
cthit/chalmers.it pull request #121
Opened 2024-09-03 22:05 UTC by GAsplund

# Key features
- Closes #62 
- Store all nav items in the database
- Settings UI for configuring nav items (admin only)

# Known issues
- There's really nothing stopping a nav category from having child items, even if the category (aka "parent") has a URL (which is considered an illegal state, but child items will just be ignored should that occur)
- There is no "dynamic" CSS sizing on the navbar width, meaning that the content could look cramped before switching to hamburger menu

2024-09-04 12:24 UTC, GAsplund commented
Okay, I'm not crazy. It seems like editing the navbar to be dynamic messes a lot with static routes. I think it propagates out to every other page but mainly is because (I think) that the root error page needs to be 100% static. I will look into this later when I have the time.

2024-10-05 15:44 UTC, Oscariremma requested changes
The user facing functionality sems to work great but see comments on the admin page. 
Not necessarily required to be fixed before merging.

2024-10-05 15:44 UTC, Oscariremma commented on src/app/[locale]/settings/navbar/page.tsx
> +      <title>Kontrollpanel - Navigering</title>
```suggestion
      <title>Control Panel - Navigation</title>
```
Use English to be consistent with the rest of the page.

2024-10-05 15:44 UTC, Oscariremma commented on src/app/[locale]/settings/navbar/page.tsx
> +      <title>Kontrollpanel - Navigering</title>
This does however seam to be a problem for all admin pages

2024-10-05 15:44 UTC, Oscariremma commented on src/app/[locale]/settings/navbar/page.tsx
This works but is quite unintuitive as we can not see any changes until reloading the page. Is it possible to reload this page somehow when changing something? With my limited understanding I am guessing it might be difficult to pass that update out of the components?
It does not matter that much as the admin pages require a UI pass later any way but still...

2024-10-05 16:40 UTC, GAsplund commented
I've implemented the changes you requested - please retest

2024-10-05 17:30 UTC, Oscariremma commented
The only thing I can think of now is that if you try to delete a category with elements it fails as a cascading delete is not performed. But this might be desirable to prevent accidental deletion?

Otherwise great!

2024-10-05 18:00 UTC, GAsplund commented
> The only thing I can think of now is that if you try to delete a category with elements it fails as a cascading delete is not performed. But this might be desirable to prevent accidental deletion?
> 
> Otherwise great!

Good point, I had not thought of that. I think we discussed cases like this earlier at some point, and concluded that it might be best if we asked for confirmation stating what would happen, so I'll probably enable cascading deletions and do that

2024-10-05 18:21 UTC, simon-wg commented
I'm unable to test-run this due to being away from my computer over the weekend. Just wanted to know if you've checked the mobile nav, everything should work fine from what I can see but you never know.

2024-10-05 19:26 UTC, GAsplund commented
> I'm unable to test-run this due to being away from my computer over the weekend. Just wanted to know if you've checked the mobile nav, everything should work fine from what I can see but you never know.

Thanks for the reminder. I've checked, and it seems to work like before.

2024-10-05 21:07 UTC, Oscariremma approved these changes
LGTM

We need to make sure we are ready to recreate the existing nav elements when deploying this.

2024-10-05 21:10 UTC, GAsplund commented
I agree. Let's hold off before pulling this on the server until we're ready to copy over

2024-10-05 21:10 UTC, merged