Feature/contactinfo
cthit/chalmers.it pull request #51
Opened 2024-02-27 18:45 UTC by simon-wg

2024-02-27 20:28 UTC, GAsplund requested changes
Looks good, but I have a few comments.

- The vertical alignment between the text and flags are a bit off:
![image](https://github.com/cthit/chalmers.it/assets/7264745/068ede87-d239-4cd8-b66b-956f0731d062)
- Check the comments made by Github Actions in the list of changed files

2024-02-28 14:19 UTC, simon-wg commented
![image](https://github.com/cthit/chalmers.it/assets/18512096/3bebe675-7d34-4c33-bba3-4dc537ada1eb)
Fixed it now I think, the padding is using rem so it should scale properly with screen size.

2024-02-28 14:19 UTC, simon-wg commented
@GAsplund

2024-02-28 22:19 UTC, GAsplund reviewed
Nicely done! I have a few suggestions to finalize and simplify it a bit. Also, don't forget to run Prettier on the files! IDEs have a tendency to ignore what Prettier says, especially for CSS files with the settings we're using right now.

2024-02-28 22:19 UTC, GAsplund commented on src/components/ContactCard/ContactCard.tsx
> +        </div>
Make this into an anchor, a button uses the browser's default sans-serif font
```suggestion
        <a className={styles.button}>
          <picture className={styles.flag}>
            <img src="/sweden.svg" alt="Swedish flag"/>
          </picture>
          <p>Svenska</p>
        </a>
        <a className={styles.button}>
          <picture className={styles.flag}>
            <img src="/uk.svg" alt="English flag"/>
          </picture>
          <p>English</p>
        </a>
```

2024-02-28 22:19 UTC, GAsplund commented on src/components/ContactCard/ContactCard.module.scss
> +}
Turn the toggles into flexboxes to align them better
```suggestion
.flag {
    width: 1.25rem;
    height: 1.25rem;
    margin-right: 0.25rem;
}

.link {
    color: var(--link-color);
}

.button {
    cursor: pointer;
    padding: 0.5rem;
    display: flex;
    align-items: center;
    p {
        font-size: 1.25rem;
    }
}

```

2024-02-28 22:19 UTC, GAsplund commented on src/components/ContactCard/ContactCard.tsx
> +      <p>Teknologsektion Informationsteknik</p>
Missing an "en" at the end
```suggestion
      <p>Teknologsektionen Informationsteknik</p>
```

2024-02-28 22:37 UTC, simon-wg commented
Thanks for the suggested changes! That's a much simpler solution than using padding. I've committed them and prettied the scss file now.

2024-02-28 22:41 UTC, GAsplund approved these changes
LGTM!

2024-02-28 22:42 UTC, merged